---
apiVersion: v1
kind: Service
metadata:
  name: honeypot
  labels:
    app: honeypot
spec:
  type: NodePort #Exposes the service as a node ports
  ports:
  - port: 8080
    name: honeypot
    protocol: TCP
    targetPort: 8080
    nodePort: 30003
  selector:
    app: honeypot