---
apiVersion: v1
kind: Service
metadata:
  name: security
  labels:
    app: security
spec:
  type: NodePort #Exposes the service as a node ports
  ports:
  - port: 1389
    name: ldap-end
    protocol: TCP
    targetPort: 1389
    nodePort: 30001
  - port: 8888
    name: web-end
    protocol: TCP
    targetPort: 8888
    nodePort: 30002
  selector:
    app: security